default: &default
  adapter: postgresql
  encoding: unicode
  username: v360
  password: senha123
  host: localhost
  pool: 5

development:
  <<: *default
  database: todo_list_app_development

test:
  <<: *default
  database: todo_list_app_test

production:
  <<: *default
  database: todo_list_app_production
  username: todo_list_app
  password: <%= ENV['TODO_LIST_APP_DATABASE_PASSWORD'] %>
